name: routes_lib
description: Pacote de gerenciamento de rotas
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5

  perfil:
    git:
      url: https://github.com/JuliaMStahl/perfil.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

