name: routes_lib
description: Pacote de gerenciamento de rotas
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5

  perfil:
    git:
      url: https://github.com/JuliaMStahl/perfil.git
      ref: master
  dashboard:
    git:
      url: https://github.com/JuliaMStahl/dashboard.git
      ref: main
  acesso:
    git:
      url: https://github.com/JuliaMStahl/acesso.git
      ref: ed499d7a2296120a00b8f0f5d982aefe2e9e6312

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

